apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java-sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java-sample
  template:
    metadata:
      labels:
        app: docker-java-sample
    spec:
      containers:
      - name: docker-java-sample
        image: docker-java-sample:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-java-sample-service
spec:
  selector:
    app: docker-java-sample
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
